### ISSUE TITLE
[Anomalie] Revoir les couleurs

### ISSUE THREAD

**Issue by Libellune** [Iron-Wolf/PixelComparator#2]
Revoir les couleurs, certains roses sur l'image ne s'ajoute pas dans la liste de droite

![animaux_chatendormi](https://cloud.githubusercontent.com/assets/26685888/24329810/956770ea-1211-11e7-8de6-f8907357b6b2.jpg)
![animaux_renard](https://cloud.githubusercontent.com/assets/26685888/24329811/9584c05a-1211-11e7-9382-fca876c2fc0d.jpg)

**Comment by Libelluneland** [comment]
![animaux_chatendormi](https://cloud.githubusercontent.com/assets/26685888/24329716/1039be16-120f-11e7-8ad6-562f517a6e5f.jpg)
![animaux_renard](https://cloud.githubusercontent.com/assets/26685888/24329717/103b164e-120f-11e7-8868-ed67351c5d62.jpg)

**Comment by Libellune** [comment]
a tester à la place du rose pastel : FFE4FF
